static_config: 
  connect:
    onprem:
      replnp:
        url: "http://kafka-connect-repl-np.dc2.np.dds.chr8s.io"
      replprd:
        url: "http://kafka-connect-api-replprd.dc2.prd.dds.chr8s.io"
      dev:
        url: "http://kafka-connect-dev.dc2.np.dds.chr8s.io"
      int:
        url: "http://kafka-connect-int.dc2.np.dds.chr8s.io"
      trn:
        url: "http://kafka-connect-api-trn.dc2.prd.dds.chr8s.io"
      prd:
        url: "http://kafka-connect-api-prd.dc2.prd.dds.chr8s.io"
      emlog:
        url: "http://kafka-connect-api-emlog.dc2.prd.dds.chr8s.io"
    azure:
      azdv:
        url: "https://kafka-connect1.dvcl01.kafka.centralus.chrazure.cloud:8083"
      azin:
        url: "https://kafka-connect1.incl01.kafka.centralus.chrazure.cloud:8083"
      aztr:
        url: "https://kafka-connect-api-trn.dc2.prd.dds.chr8s.io"
      azpr:
        url: "https://kafka-connect-api-azpr.dc2.prd.dds.chr8s.io"
  schema:
    dev:
      url: "http://kafkadvschemacl01.chrobinson.com:8081"
    int:
      url: "http://kafkainschemacl01.chrobinson.com:8081"
    trn:
      url: "http://kafkatrschemacl01.chrobinson.com:8081"
    prd:
      url: "http://kafkaprschemacl01.chrobinson.com:8081"
    azdv:
      url: "https://schema-registry.dvcl01.kafka.centralus.chrazure.cloud:8081"
    azin:
      url: "https://schema-registry01.incl01.kafka.centralus.chrazure.cloud:8081"
    aztr:
      url: "https://schema-registry01.trcl01.kafka.centralus.chrazure.cloud:8081"
    azpr:
      url: "https://schema-registry.prcl01.kafka.centralus.chrazure.cloud:8081"
  prometheus:
    dds-np:
      url: "http://ddsmetrics.dc2.np.dds.chr8s.io"
    dds-prd:
      url: "http://ddsmetrics.dc2.prd.dds.chr8s.io"
