archivelabs:
  url: https://api.archivelab.org/v1
inshortsapi:
  url: https://inshortsapi.vercel.app/news
me:
  url: http://localhost:8080
  authentication:
    token:
      token: testingtoken
metwo:
  url: http://localhost:8080
  authentication:
    basic:
      username: user
      password: testing
