routes:
  archivelabs:
    proxy:
      url: https://api.archivelab.org/v1
      timeout: 5000
      security:
        whitelist:
          methods:
          - GET
  inshortsapi:
    proxy: 
      url: https://inshortsapi.vercel.app/news
      timeout: 5000
  local:
    proxy:
      url: http://localhost:8082
      security:
        client:
          digest:
          - username: user
            password: mypassword
            whitelist:
              methods:
              - GET
