[book]
authors = []
language = "en"
multilingual = false
src = "src"

[build]
create-missing = true

[output.html.fold]
enable = false
level = 0

[output.html]
git-repository-url = "https://github.com/findelabs/proxima"
edit-url-template = "https://github.com/findelabs/proxima/edit/master/docs/{path}"
